### ISSUE TITLE
[fail2ban]: wrong log path?

### ISSUE THREAD

**Issue by myanesp** [Madh93/homelab#1]
Hi! :canary_islands: 

First of all I want to say that thanks for making this repo available to everyone, because thanks to that I've been able to run Traefik and now fail2ban with no hassle :)

The issue is that when I was trying fail2ban along with Traefik, I tried to ban myself (using a commercial VPN) but with no success. I managed to solve it when I realise that in [jaild.d/traefik.conf](https://github.com/Madh93/homelab/blob/master/fail2ban/jail.d/traefik.conf), the logpath was pointing `traefik.log`. I don't know if this changes through different installations, but the Traefik log that stores the access for me is under `access.log`, not `traefik.log`.

my `traefik.log`:
```
$ cat config/logs/traefik.log
time="2024-01-27T12:36:49+01:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-01-27T12:36:53+01:00" level=warning msg="No domain found in rule HostRegexp(`{host:.+}`), the TLS options applied for this router will depend on the SNI of each request" routerName=errorpages@file entryPointName=websecure
```

my `access.log`:
```
$ cat config/logs/access.log 
165.154.104.88 - - [27/Jan/2024:11:38:00 +0000] "GET / HTTP/1.1" 403 0 "-" "-" 1 "errorpages@file" "-" 69ms
165.154.104.88 - - [27/Jan/2024:11:38:19 +0000] "GET /favicon.ico HTTP/1.1" 403 0 "-" "-" 2 "errorpages@file" "-" 0ms
165.154.104.88 - - [27/Jan/2024:11:38:20 +0000] "GET /robots.txt HTTP/1.1" 403 0 "-" "-" 3 "errorpages@file" "-" 0ms
192.168.50.1 - - [27/Jan/2024:11:39:25 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 4 "dav@file" "-" 1ms
192.168.50.1 - juan [27/Jan/2024:11:39:28 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 5 "dav@file" "-" 0ms
192.168.50.1 - juan [27/Jan/2024:11:39:32 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 6 "dav@file" "-" 0ms
```

So when I change this: `logpath = /var/log/traefik/traefik.log` to this `logpath = /var/log/traefik/access.log`, fail2ban started working flawlessly.

Thanks again for sharing your files :)

**Comment by Madh93** [comment]
Thank you for kind words!

According to the Traefik documentation, access logs are, by default, written to the standard output. To direct logs to a log file, the [filePath](https://doc.traefik.io/traefik/observability/access-logs/#filepath) option should be used.

I enabled this option in https://github.com/Madh93/homelab/commit/4dd5a50b3200263c202fb3549375efa86f59d23c to save logs in a file that Fail2Ban could read. I defined the filename as [traefik.log](https://github.com/Madh93/homelab/blob/master/traefik/docker-compose.yml#L45).

I've seen that you migrated from Docker labels to dynamic configuration (https://github.com/myanesp/homelab/commit/198720a736e698804d07202c43cee3b5103e95e4) . Is it possible that when you migrated your Traefik configuration, you changed the log file name from `traefik.log` to `access.log`?

PS: another way to test Fail2ban is to use your 4G/5G mobile data connection instead of VPN :smile:

**Comment by myanesp** [comment]
Hi there!

Sorry for the delay. Finally, I ended stopping fail2ban service as I need to deep more into it and the configuration that would suit me better. So maybe was a misunderstanding on my side. Thanks again for publishing your homelab :)
